{% set name = "pytest-picked" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b39cd43b1f5e6efd2fc896f318e23c2c77effde8dd6efa58653a2940d8a384d9

build:
  noarch: python
  number: 0
  script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
    - pytest >=3.7.0
  run:
    - python >=3.7
    - pytest >=3.7.0

test:
  imports:
    - pytest_picked

about:
  home: https://github.com/anapaulagomes/pytest-picked
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Run the tests related to the changed files
  description: Run the tests related to the changed files

extra:
  recipe-maintainers:
    - nicoddemus
