{% set name = "pytest-picked" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1c7c070d622403e109d2e8cd8054e44c117065b5ab79dc39cb5697ffd867309f

build:
  noarch: python
  number: 0
  script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
    - pytest >=3.5.0
  run:
    - python >=3.5
    - pytest >=3.5.0

test:
  imports:
    - pytest_picked

about:
  home: https://github.com/anapaulagomes/pytest-picked
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Run the tests related to the changed files
  description: Run the tests related to the changed files

extra:
  recipe-maintainers:
    - nicoddemus
