travis:
  secure:
    BINSTAR_TOKEN: BEi7H3G5IaXKgKtrG+ZAMTyfPXgnrmVXplKVkktnBmH9BJVFc8eor2IEIQrNuGXSAeFbHdOXYLW5ppt3JOB6QzDkUVgZ5lZj2sry6+hVXMWCqqyTKUySEdOnFInE9dnfp4aUyTMepzxO4bhJ7XADnqgHmEZADOZFUXWtTLnrDrCQIdhqmQtqZSUlPsB8J/U76/aVU49xnW8Kd9z9coB81X1Ue/qqN3O4126Ir+pUFEXC7J8UvtaycXZvHCVIi0kmxQLckdngjsZ1iwhINwOOjfL4KpUPNDrjkPCcaKrxbTA9/q2Sj5NywHBB4bzGA1cdN0cb4G1u2fmORXMOAOzJpBnlfHe9jm82AcJXi6FahU06h20oi5ObhE8x7mq+ZZA28epS8feMm8GkjZvNJMzCN5LKVy3s1nh7Fj1O4RGx0dlZA67O3fSLYL0awPxCHeaJzwGVjs7q0ZR0oMIdlXbQheVwxBNxCunEBhZiNm8zUB62szhim/vCusylY+aMicdXucI8Pqxit8d8pWN0ybp2MkShH7n5uEGbABtjljmVXDmGbem+geZXWS5vhLUuaT6O08hdvopVXWwvdhP1et8VKxq4tqU8aJl85gI69xsq9aDMY6lYxeSZ8SUnqKQjumBuTgWIT/uYqYlCuBIENC/lQpaWsozC72cR+XceJwCGvWI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
